apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissa-trading-tinkoff-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissa-trading-tinkoff-api-service
  template:
    metadata:
      labels:
        app: lissa-trading-tinkoff-api-service
    spec:
      containers:
        - name: auth-service
          image: belaquaaa/lissa-trading-tinkoff-api-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: AUTH_SERVICE_URL
              value: http://lissa-trading-auth-service:8081
            - name: USER_SERVICE_URL
              value: http://lissa-trading-tinkoff-api-service:8080
            - name: TINKOFF_API_SERVICE_URL
              value: http://lissa-trading-tinkoff-api-service:8082
            - name: TINKOFF_TOKEN
              value: "token"
            - name: IS_SANDBOX_MODE
              value: "true"