apiVersion: v1
kind: Service
metadata:
  name: lissa-trading-tinkoff-api-service
spec:
  selector:
    app: lissa-trading-tinkoff-api-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
