server:
  port: ${SERVER_PORT}

api:
  isSandBoxMode: ${IS_SANDBOX_MODE}
  tinkoff-token: ${TINKOFF_TOKEN}

logging:
  level:
    root: INFO

security:
  internal:
    token: ${SECURITY_INTERNAL_TOKEN}

integration:
  rest:
    auth-service-url: ${AUTH_SERVICE_URL}

springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH}
