server:
  port: 8082

api:
  isSandBoxMode: true
  tinkoff-token: "token"

logging:
  level:
    root: INFO

security:
  internal:
    token: dGlua29mZkFwaS1pbnRlcm5hbC1rZXk=

integration:
  rest:
    auth-service-url: http://localhost:8081
    tinkoff-api-service-url: http://localhost:8082
    user-service:
      url: http://localhost:8080
      token: bGlzc2EtdHJhZGluZy11c2VyLXNlcnZpY2U=
    analytics-service:
      token: YW5hbHl0aWNzLWludGVybmFsLWtleQ==
  rabbit: