server:
  port: 8082

api:
  isSandBoxMode: true
  tinkoff-token: "token"

logging:
  level:
    root: INFO

security:
  internal:
    token: ZEdsdWEyOW1aa0Z3YVMxcGJuUmxjbTVoYkMxclpYaz0K

integration:
  rest:
    auth-service-url: http://localhost:8081

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://103.249.132.74:9411/api/v2/spans