server:
  port: ${SERVER_PORT}

api :
  isSandBoxMode : ${IS_SANDBOX_MODE}
  tinkoff-token: ${TINKOFF_TOKEN}

logging:
  level:
    root: INFO

security:
  internal:
    token: ${SECURITY_INTERNAL_TOKEN}

integration:
  rest:
    auth-service-url: ${AUTH_SERVICE_URL}
    user-service-url: ${USER_SERVICE_URL}
    tinkoff-api-service-url: ${TINKOFF_API_SERVICE_URL}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        exclude: '*'
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}