server:
  port: 8082

api :
  isSandBoxMode : true
  tinkoff-token: "token"

logging:
  level:
    root: INFO

integration:
  rest:
    auth-service-url: http://localhost:8081
    user-service-url: http://localhost:8080
    tinkoff-api-service-url: http://localhost:8082
  rabbit: