apiVersion: v1
kind: ConfigMap
metadata:
  name: lissa-trading-tinkoff-api-service-config
data:
  SERVER_PORT: "8082"
  USER_SERVICE_URL: "http://lissa-trading-user-service:8080"
  TINKOFF_API_SERVICE_URL: "http://lissa-trading-tinkoff-api-service:8082"
  ZIPKIN_URL: "http://103.249.132.74:9411/api/v2/spans"
  AUTH_SERVICE_URL: "http://lissa-trading-auth-service:81"
  LOKI_URL: "http://loki:3100"
  IS_SANDBOX_MODE: "true"
  LOGGING_LEVEL_ROOT: "INFO"
  SWAGGER_PATH: "swagger-ui/tinkoff-api-service"
