apiVersion: v1
kind: ConfigMap
metadata:
  name: lissa-trading-tinkoff-api-service-config
data:
  SERVER_PORT: "8082"
  AUTH_SERVICE_URL: "http://lissa-trading-auth-service:81"
  USER_SERVICE_URL: "http://lissa-trading-user-service:83"
  TINKOFF_API_SERVICE_URL: "http://lissa-trading-tinkoff-api-service:82"
  IS_SANDBOX_MODE: "true"
  LOGGING_LEVEL_ROOT: "INFO"
  SWAGGER_PATH: "swagger-ui/tinkoff-api-service"
