apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissa-trading-tinkoff-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissa-trading-tinkoff-api-service
  template:
    metadata:
      labels:
        app: lissa-trading-tinkoff-api-service
    spec:
      containers:
        - name: tinkoff-api-service
          image: belaquaaa/lissa-trading-tinkoff-api-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: lissa-trading-tinkoff-api-service-config
            - secretRef:
                name: lissa-trading-tinkoff-api-service-secret
