apiVersion: v1
kind: Service
metadata:
  name: lissa-trading-tinkoff-api-service
spec:
  selector:
    app: lissa-trading-tinkoff-api-service
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082
      nodePort: 30082
  type: NodePort
